services:
  - type: web
    name: autism-screening-api
    runtime: python
    plan: free
    rootDir: summative/API
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
